/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "xitlmkambdtpkkxzudpm"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhpdGxta2FtYmR0cGtreHp1ZHBtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjczNDQ4NjQsImV4cCI6MjA4MjkyMDg2NH0.wTDAeGPpfCsLFSxq_k1vxoXaDHv-wOz-uUqz1_wyt-U"